/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        UDPConnection connection = UDPConnection.getInstance();

        // Escuchar mensajes 
        connection.setPort(5000);
        connection.start();

        // Enviar mensaje 
        connection.sendDatagramt("Hola desde aca", "172.16.15.132", 5000);

    }
}
