/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        UDPConnection connection = UDPConnection.getInstance();

        // Escuchar mensajes 
        connection.setPort(5000);
        connection.start();

        // Enviar mensaje 

        connection.sendDatagramt("Hola desde acá", "127.0.0.1", 5000);

    }
}
